# Use to start interactive development shell using:
#   docker-compose -f .\docker-compose-dev.yml run aoc-2023

name: aoc-2023

services:
  aoc-2023:
    image: rust
    entrypoint: /bin/bash
    working_dir: /src
    tty: true
    volumes:
      - ./:/src